
USE QLHANG
GO

CREATE TABLE VATTU(
    MAVT varchar(10) PRIMARY KEY, 
    TENVT nvarchar(50),
    DVTINH nvarchar(50),
    SLCON INT
);

CREATE TABLE HDBAN(
    MAHD varchar(10) PRIMARY KEY, 
    NGAYXUAT DATE,
    HOTENKHACH nvarchar(50)
);

CREATE TABLE HANGXUAT(
    MAHD varchar(10),
    MAVT varchar(10),
    DONGIA INT,
    SLBAN INT,
    CONSTRAINT HANGXUAT_PK PRIMARY KEY (MAHD, MAVT)
);

ALTER TABLE HANGXUAT ADD CONSTRAINT FK_HANGXUAT_HDBAN
FOREIGN KEY (MAHD) REFERENCES HDBAN (MAHD);
ALTER TABLE HANGXUAT ADD CONSTRAINT FK_HANGXUAT_VATTU
FOREIGN KEY (MAVT) REFERENCES VATTU (MAVT);

INSERT INTO VATTU VALUES
('VT_GV', 'GACH', 'VIEN', 500000),
('VT_XM', 'XI-MANG', 'BAO', 2000);

INSERT INTO HDBAN VALUES
('HD01', '2022-12-14', 'Bui Henry'),
('HD02', '2022-11-15', 'Duong Mai Tra My');

INSERT INTO HANGXUAT VALUES
('HD01', 'VT_GV', 4000, 100),
('HD01', 'VT_XM', 25000, 50),
('HD02', 'VT_GV', 6200, 90),
('HD02', 'VT_XM', 28000, 30);


-- CAU 2 
SELECT TOP 1
MAHD, SUM(SLBAN * DONGIA) AS N'Tổng Tiền HÓA ĐƠN'
FROM HANGXUAT
GROUP BY MAHD
ORDER BY SUM(SLBAN * DONGIA) Desc;


-- CAU 4 
CREATE PROCEDURE p4 
@thang int, @nam int 
AS
SELECT 
SUM(SLBAN * DONGIA)
FROM HANGXUAT HX
INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
where MONTH(HD.NGAYXUAT) = @THANG AND YEAR(HD.NGAYXUAT) = @NAM;